#!/usr/bin/env python3
"""
Generate the SPIKES tile (TileSubtype.SPIKES) — a bed of iron spikes sunk into a pit.

Writes a base64 PNG into `.spikes` in components/Tile.module.css.
AFTER running this, re-run `python3 scripts/gen-spike-holes.py` so the retracted-bed art
still has its sockets where the spikes actually stood.

    python3 scripts/gen-spikes.py --write
    python3 scripts/gen-spike-holes.py            # then paste its BASE64 into .spikeHoles

WHY THIS EXISTS. The bed used to be generated by a `scratchpad/gen_spikes.js` that is gone,
so the art was unreproducible — any tweak meant hand-editing 32x32 pixels through a base64
blob. It is regenerated here instead, and the geometry lives in ROWS below where it can be
retuned in one line.

THE BUG THIS WAS WRITTEN TO FIX. The original bed drew its spikes over rows 6-29 of a 32px
tile whose pit runs 2-29, leaving four empty rows along the back edge and putting all the
visual mass at the bottom. In game that read as spikes sliding off the bottom of their own
tile. The field now fills the pit: the backmost row's tips reach the pit's top edge and the
front row's feet sit on its bottom edge.

FORCED PERSPECTIVE. The camera looks at the floor from a shallow angle, so rows further back
are drawn shorter, narrower, dimmer and closer together — same convention as the sockets in
gen-spike-holes.py being squashed 2:1. Rows are staggered horizontally by half a spacing so
the player sees BETWEEN the spikes of the row in front; without the stagger the columns line
up and the bed reads as three stripes.

DRAW ORDER IS BACK TO FRONT, and it matters: a front spike must occlude the one behind it.
Painting front-to-back leaves the back row's tips punched through the front blades.
"""
import argparse
import base64
import io
import pathlib
import re

from PIL import Image

CSS = pathlib.Path(__file__).resolve().parents[1] / "components" / "Tile.module.css"

SIZE = 32
# The pit's rim. A uniform 2px border, matching the tile this replaces — the lighting
# convention lives in the bevel and the blades, not in the rim.
LIP = (104, 86, 60)
BEVEL = (52, 41, 29)
PIT = (33, 26, 20)
PIT_DEEP = (18, 14, 11)
PIT_INSET = 2

# Iron. Blades are lit from the upper left: highlight down the left edge, shadow down the
# right, mid tone between. Back rows are lerped toward the pit colour (aerial perspective)
# so depth survives the field-of-view dimming the tile gets in game.
IRON_LIT = (176, 178, 186)
IRON_MID = (124, 126, 134)
IRON_DARK = (46, 46, 52)
IRON_SHADE = (82, 82, 90)
# There is deliberately no blood. The tile this replaces had a few rust-red pixels and every
# attempt to keep them read as a distracting spot rather than as gore — at 32px, on a tile the
# player passes dozens of times a run, one warm pixel on a cold grey blade is just noise.

# A blade's WIDTH IN PIXELS, tip first. Odd numbers only, so every blade has a centre column.
#
# The silhouette has to be a TRIANGLE that widens most of the way down. Two earlier shapes both
# failed for the same underlying reason — too much constant-width shaft:
#   linear taper 5,4,4,3,3,2,2,1,1  -> a cone, read as a bowling pin
#   nub-and-shaft 1,1,3,3,3,3,5,5   -> a wide pillar with a spot on top, read as a chess pawn
# Widening in three or four steps across the full height is what reads as iron at 32px. The
# widest step is deliberately wide enough that neighbouring bases nearly meet, which is what
# turns nine separate spikes into one BED — the hand-drawn original did the same thing.
#
# BASE WIDTH IS CONSTRAINED BY THE RETRACTED TILE, not by how this one looks. gen-spike-holes.py
# clusters spike feet within 2.2px into a single socket, so two blades whose bases come closer
# than ~3px stop reading as two holes. The back row is therefore 5px at the base where the other
# two are 7px — which is also just correct perspective for the row furthest away. A first pass
# gave every row a 7px base at 8px spacing, and the back row's three feet merged into one
# 21-pixel-wide socket.
PROFILES = {
    8: (1, 1, 3, 3, 3, 5, 5, 5),
    9: (1, 1, 3, 3, 5, 5, 5, 7, 7),
    10: (1, 1, 3, 3, 3, 5, 5, 7, 7, 7),
}

# One entry per row of spikes, BACK TO FRONT. `foot` is the y the blades stand on, `height`
# indexes PROFILES, `xs` are their centre columns, and `depth` is how far the row fades toward
# the pit colour (0 = full iron).
#
# THREE rows, feet 8-9px apart, heights growing 8 -> 10 toward the camera. Back row's tip lands
# on the first drawable row (10 - 8 + 1 = 3) and the front row's feet one row short of the last,
# so the bed fills its tile top to bottom — that is the whole point of the rewrite, and the
# original's 6-29 field against a 2-29 pit is the bug being fixed. Check these numbers before
# touching anything else here.
#
# FEET AND CENTRES ARE KEPT CLEAR OF THE PIT EDGE ON PURPOSE, and it is not about this tile: it
# is about the retracted one. gen-spike-holes.py stamps a socket at every spike foot, and a
# socket is wider and taller than the foot that made it (ellipse 2.6 x 1.3, collar 1.42x). Feet
# on row 28 or centres past x=25 produce sockets sliced in half by the rim — which is what made
# the first pass's bottom row read as a row of broken cups.
#
# Four rows was tried first and was worse twice over: at 6-7px spacing each row's tip landed
# inside the shaft of the row behind it, so the bed read as three diagonal zigzags instead of
# rows, and squeezing blades short enough to avoid that made them stubby enough to read as
# gravel. Three taller rows is also what the hand-drawn original did.
#
# The middle row has TWO blades, sitting in the gaps of the three-blade rows either side — the
# A-B-A pattern the eye reads as depth. Positions are written out rather than derived from a
# count and a phase offset: the derived version put the middle row's third blade at x=29, off
# the drawable area, so it was silently dropped and the row was quietly asymmetric.
ROWS = [
    {"foot": 10, "height": 8, "xs": (8, 16, 24), "depth": 0.38},
    {"foot": 18, "height": 9, "xs": (11, 20), "depth": 0.18},
    {"foot": 27, "height": 10, "xs": (7, 16, 25), "depth": 0.00},
]


def lerp(a, b, t):
    return tuple(round(ai + (bi - ai) * t) for ai, bi in zip(a, b))


def base_tile():
    """The pit: rim, bevel, and a floor that darkens toward the back."""
    im = Image.new("RGB", (SIZE, SIZE), LIP)
    px = im.load()
    lo, hi = PIT_INSET, SIZE - PIT_INSET - 1
    for y in range(lo, hi + 1):
        for x in range(lo, hi + 1):
            on_edge = x in (lo, hi) or y in (lo, hi)
            if on_edge:
                # Bevel: the pit wall. Lit on the near (bottom/right) faces, since the floor
                # beyond the rim is what catches the light from above.
                px[x, y] = BEVEL
            else:
                # Floor falls off toward the back so the bed has somewhere to recede into.
                t = 1.0 - (y - lo) / max(1, hi - lo)
                px[x, y] = lerp(PIT, PIT_DEEP, t * 0.5)
    return im


def draw_spike(px, cx, foot, height, depth):
    """One blade, drawn tip-down-to-foot from its PROFILES entry."""
    lit = lerp(IRON_LIT, PIT, depth)
    mid = lerp(IRON_MID, PIT, depth)
    dark = lerp(IRON_DARK, PIT, depth)
    shade = lerp(IRON_SHADE, PIT, depth)

    profile = PROFILES[height]
    lo, hi = PIT_INSET + 1, SIZE - PIT_INSET - 2
    centre = int(round(cx))
    for i, w in enumerate(profile):
        y = foot - (len(profile) - 1 - i)  # profile[0] is the tip
        if not (lo <= y <= hi):
            continue
        half = (w - 1) // 2
        for x in range(centre - half, centre + half + 1):
            if not (lo <= x <= hi):
                continue
            # Ramp across the blade so it reads as a round-ish shaft lit from the upper left.
            # Keyed on position rather than on width: `mid if w == 3 else shade` filled every
            # 5px and 7px blade with the darkest interior, which made the front row — the
            # widest and the one meant to be brightest — the murkiest thing on the tile.
            if w == 1:
                col = lit
            else:
                u = (x - (centre - half)) / (w - 1)
                col = lit if u <= 0.2 else mid if u <= 0.5 else shade if u < 0.85 else dark
            px[x, y] = col


def build():
    im = base_tile()
    px = im.load()
    for row in ROWS:
        for cx in row["xs"]:
            draw_spike(px, cx, row["foot"], row["height"], row["depth"])
    return im


def to_b64(im):
    buf = io.BytesIO()
    im.save(buf, format="PNG", optimize=True)
    return base64.b64encode(buf.getvalue()).decode(), len(buf.getvalue())


def write_css(b64):
    css = CSS.read_text()
    pat = re.compile(r"(\.spikes \{.*?base64,)([A-Za-z0-9+/=]+)", re.S)
    if not pat.search(css):
        raise SystemExit("could not find the .spikes base64 in " + str(CSS))
    CSS.write_text(pat.sub(lambda m: m.group(1) + b64, css, count=1))
    print(f"wrote .spikes in {CSS}")


def preview(im, path, scale=12):
    """Upscaled strip for eyeballing: three tiles side by side at full brightness, then the
    same dimmed to 0.6 — the field-of-view filter puts these tiles at 55-80% in game, and
    art judged at 100% has been wrong here before (see gen-spike-holes.py)."""
    strip = Image.new("RGB", (SIZE * 3, SIZE * 2), (20, 26, 20))
    for i in range(3):
        strip.paste(im, (SIZE * i, 0))
    dim = Image.eval(im, lambda v: int(v * 0.6))
    for i in range(3):
        strip.paste(dim, (SIZE * i, SIZE))
    out = strip.resize((strip.width * scale, strip.height * scale), Image.NEAREST)
    out.save(path)
    print(f"preview -> {path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="patch .spikes in Tile.module.css")
    ap.add_argument("--preview", metavar="PNG", help="write an upscaled preview strip")
    args = ap.parse_args()

    im = build()
    b64, nbytes = to_b64(im)
    print(f"png {nbytes} bytes")
    if args.preview:
        preview(im, args.preview)
    if args.write:
        write_css(b64)
    else:
        print("BASE64:" + b64)


if __name__ == "__main__":
    main()
