#!/usr/bin/env python3
"""Decode the per-tile water textures for the terrain sheets.

The terrain sheets (lib/terrain_sheet.ts) fill their water with the same 32x32 pixel-art
textures the classic tiles paint (the .shallowWater and .deepWater data URIs in
components/Tile.module.css), so a sheet-drawn pool keeps the game's look and only its
shape changes. (Lava is generated procedurally instead and needs no texture.) Those
textures are tiny palettes, so they are written out as a palette plus one index character
per pixel, which the sheet builder can read synchronously without decoding an image.

Usage:  python3 scripts/gen-terrain-textures.py   (needs pillow)
Rewrites lib/terrain_textures.ts. Rerun it whenever one of those CSS textures changes.
"""

import base64
import io
import pathlib
import re

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSS = ROOT / "components" / "Tile.module.css"
OUT = ROOT / "lib" / "terrain_textures.ts"
TEXTURES = [("shallowWater", "SHALLOW"), ("deepWater", "DEEP")]
INDEX_CHARS = "0123456789abcdefghijklmnopqrstuvwxyz"


def decode(css: str, cls: str) -> Image.Image:
    m = re.search(r"\n\." + cls + r" \{.*?base64,([A-Za-z0-9+/=]+)", css, re.S)
    if not m:
        raise SystemExit(f"no data URI found for .{cls}")
    return Image.open(io.BytesIO(base64.b64decode(m.group(1)))).convert("RGB")


def main() -> None:
    css = CSS.read_text()
    blocks = []
    for cls, name in TEXTURES:
        im = decode(css, cls)
        w, h = im.size
        pixels = list(im.getdata())
        palette = sorted(set(pixels), key=pixels.index)
        if len(palette) > len(INDEX_CHARS):
            raise SystemExit(f".{cls} has too many colours for the index alphabet")
        rows = [
            "".join(INDEX_CHARS[palette.index(pixels[y * w + x])] for x in range(w))
            for y in range(h)
        ]
        pal = ", ".join(f"[{r}, {g}, {b}]" for r, g, b in palette)
        body = "\n".join(f'    "{row}",' for row in rows)
        blocks.append(
            f"export const {name}_TEXTURE: TerrainTexture = {{\n"
            f"  size: {w},\n"
            f"  palette: [{pal}],\n"
            f"  rows: [\n{body}\n  ],\n"
            f"}};\n"
        )
    header = (
        "// GENERATED by scripts/gen-terrain-textures.py from the .shallowWater and .deepWater\n"
        "// data URIs in components/Tile.module.css. Do not edit by hand; rerun the script.\n"
        "//\n"
        "// Each texture is a palette plus one index character per pixel (0-9 then a-z).\n\n"
        "export interface TerrainTexture {\n"
        "  size: number;\n"
        "  palette: ReadonlyArray<readonly [number, number, number]>;\n"
        "  rows: readonly string[];\n"
        "}\n\n"
    )
    OUT.write_text(header + "\n".join(blocks))
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
