import {
  advanceToNextFloor,
  initializeGameStateForMultiTier,
  type GameState,
} from "../map";
import { hashStringToSeed, mulberry32, withPatchedMathRandom } from "../rng";
import { DateUtils } from "../date_utils";

/**
 * Build today's daily-challenge floor-2 state, carrying over the inventory
 * and hero stats from a completed tutorial run.
 *
 * Strategy: synthesize a fresh "floor 1 done" state using the same seed +
 * initializer the real daily flow uses (so `floorChestAllocation`, etc. are
 * populated correctly), overlay the tutorial's inventory onto it, then call
 * the existing `advanceToNextFloor` primitive — which generates the
 * floor-2 map with a floor-specific seed and preserves the carried
 * inventory automatically.
 *
 * What carries:
 *   - heroHealth / heroMaxHealth / heroAttack
 *   - hasSword / hasShield / hasKey
 *   - foodCount / rockCount / runeCount / potionCount
 *
 * What resets (per-floor):
 *   - hasExitKey (each floor has its own exit key)
 *   - mapData, enemies, npcs (generated by advanceToNextFloor)
 *   - stats (real-daily stats start fresh; tutorial doesn't count)
 */
export function buildDailyFloor2FromTutorial(
  tutorialState: GameState
): GameState {
  const localToday = DateUtils.getTodayString();
  const seed = hashStringToSeed(localToday);

  // Step 1: Build a floor 1 state the same way the daily route does. We
  // need it for floorChestAllocation and other floor-1 fields that
  // advanceToNextFloor reads when generating floor 2.
  const rng = mulberry32(seed);
  const floor1 = withPatchedMathRandom(rng, () => {
    return initializeGameStateForMultiTier(1);
  });
  if (!floor1) {
    throw new Error(
      "buildDailyFloor2FromTutorial: failed to initialize daily floor 1"
    );
  }

  // Step 2: Overlay the tutorial's inventory + hero stats onto floor 1.
  // Per-floor flags (exit key, win) are reset.
  const carried: GameState = {
    ...floor1,
    heroHealth: tutorialState.heroHealth,
    heroMaxHealth: tutorialState.heroMaxHealth,
    heroAttack: tutorialState.heroAttack,
    hasSword: tutorialState.hasSword,
    hasShield: tutorialState.hasShield,
    hasKey: tutorialState.hasKey,
    hasExitKey: false,
    foodCount: tutorialState.foodCount ?? 0,
    rockCount: tutorialState.rockCount ?? 0,
    runeCount: tutorialState.runeCount ?? 0,
    potionCount: tutorialState.potionCount ?? 0,
    mode: "daily",
    allowCheckpoints: false,
    win: false,
  };

  // Step 3: Advance to floor 2 — generates the floor-2 map with the
  // floor-specific seed, preserves the inventory we just overlaid.
  const floor2 = advanceToNextFloor(carried, seed);
  floor2.mode = "daily";
  floor2.allowCheckpoints = false;
  return floor2;
}
