export interface CrosswordEntry {
  word: string;
  clue: string;
}

export const WORD_BANK: CrosswordEntry[] = [
  { word: "abbey", clue: "The office or dominion of an abbot or abbess" },
  { word: "able", clue: "Having the necessary powers or the needed resources to accomplish a task" },
  { word: "about", clue: "On all sides" },
  { word: "above", clue: "Directly overhead" },
  { word: "absurd", clue: "Contrary to reason or propriety" },
  { word: "abuse", clue: "Improper treatment or usage" },
  { word: "across", clue: "From one side to the other" },
  { word: "action", clue: "The effort of performing or doing something" },
  { word: "active", clue: "Having the power or quality of acting" },
  { word: "acute", clue: "Brief, quick, short" },
  { word: "added", clue: "combined or joined to increase in size or quantity or scope" },
  { word: "afford", clue: "To incur, stand, or bear without serious detriment, as an act which might under other circumstances be..." },
  { word: "again", clue: "Another time: indicating a repeat of an action" },
  { word: "aged", clue: "Old" },
  { word: "agent", clue: "One who exerts power, or has the power to act" },
  { word: "aging", clue: "The process of becoming older or more mature" },
  { word: "agony", clue: "Extreme pain" },
  { word: "agreed", clue: "In harmony" },
  { word: "ahead", clue: "At or towards the front" },
  { word: "aim", clue: "The pointing of a weapon, as a gun, a dart, or an arrow, or object, in the line of direction with the..." },
  { word: "alarm", clue: "A summons to arms, as on the approach of an enemy" },
  { word: "alert", clue: "Attentive" },
  { word: "alien", clue: "A person, animal, plant, or other thing which is from outside the family, group, organization, or..." },
  { word: "alive", clue: "Having life" },
  { word: "allied", clue: "Joined as allies" },
  { word: "alloy", clue: "A metal that is a combination of two or more elements, at least one of which is a metal, a base metal" },
  { word: "almost", clue: "Very close to, but not quite" },
  { word: "altar", clue: "A table or similar flat-topped structure used for religious rites" },
  { word: "amazed", clue: "Astonished or confounded with fear, surprise, or wonder" },
  { word: "amused", clue: "Pleasurably entertained" },
  { word: "angry", clue: "Displaying or feeling anger" },
  { word: "annals", clue: "A relation of events in chronological order, each event being recorded under the year in which it happened" },
  { word: "answer", clue: "A response or reply" },
  { word: "anti", clue: "Opposed to something" },
  { word: "any", clue: "To even the slightest extent, at all" },
  { word: "aortic", clue: "Of or pertaining to the aorta or the aortic valve" },
  { word: "apt", clue: "Suitable" },
  { word: "arbor", clue: "A shady sitting place or pergola usually in a park or garden, surrounded by climbing shrubs, vines or..." },
  { word: "arid", clue: "Very dry" },
  { word: "arms", clue: "Weaponry, weapons" },
  { word: "ash", clue: "Solid remains of a fire" },
  { word: "aside", clue: "To or on one side so as to be out of the way" },
  { word: "ask", clue: "To request or petition" },
  { word: "asking", clue: "That asks" },
  { word: "asks", clue: "To request or petition" },
  { word: "aspect", clue: "Any specific feature, part, or element of something" },
  { word: "assay", clue: "Trial, attempt" },
  { word: "asset", clue: "A thing or quality that has value, especially one that generates cash flows" },
  { word: "assist", clue: "To help" },
  { word: "assume", clue: "To authenticate by means of belief" },
  { word: "ate", clue: "An elder sister" },
  { word: "atlas", clue: "A bound collection of maps often including tables, illustrations or other text" },
  { word: "attack", clue: "An attempt to cause damage, injury to, or death of an opponent or enemy" },
  { word: "attend", clue: "Senses relating to caring for or waiting on someone, or accompanying or being present" },
  { word: "audio", clue: "Focused on audible sound, as opposed to sight" },
  { word: "august", clue: "Awe-inspiring, majestic, noble, venerable" },
  { word: "autumn", clue: "Traditionally the third of the four seasons, when deciduous trees lose their leaves, and temperatures and..." },
  { word: "avenue", clue: "A broad street, especially one bordered by trees or, in cities laid out in a grid pattern, one that is on..." },
  { word: "away", clue: "From a place, hence" },
  { word: "awful", clue: "Very bad" },
  { word: "axes", clue: "A tool for felling trees or chopping wood etc" },
  { word: "cap", clue: "A close-fitting hat, either brimless or peaked" },
  { word: "car", clue: "A wheeled vehicle that moves independently, with at least three wheels, powered mechanically, steered by a..." },
  { word: "dam", clue: "A structure placed across a flowing body of water to stop the flow or part of the flow, generally for..." },
  { word: "den", clue: "A small cavern or hollow place in the side of a hill, or among rocks" },
  { word: "dim", clue: "Not bright or colorful" },
  { word: "due", clue: "Owed or owing" },
  { word: "dye", clue: "A colourant, especially one that has an affinity to the substrate to which it is applied" },
  { word: "eat", clue: "To ingest" },
  { word: "ego", clue: "The self, especially with a sense of self-importance" },
  { word: "end", clue: "The terminal point of something in space or time" },
  { word: "fat", clue: "Carrying more fat than usual on one's body" },
  { word: "fun", clue: "Amusement, enjoyment or pleasure" },
  { word: "gap", clue: "An opening in anything made by breaking or parting" },
  { word: "gel", clue: "A semi-solid to almost solid colloid of a solid and a liquid, such as jelly, cheese or opal" },
  { word: "god", clue: "A deity or supreme being" },
  { word: "not", clue: "Negates the meaning of the modified verb" },
  { word: "old", clue: "Of an object, concept, relationship, etc" },
  { word: "one", clue: "The digit or figure 1" },
  { word: "out", clue: "Away from the inside or centre" },
  { word: "own", clue: "Belonging to" },
  { word: "pace", clue: "A step" },
  { word: "pack", clue: "A bundle made up and prepared to be carried" },
  { word: "packed", clue: "Put into a package" },
  { word: "pact", clue: "An agreement" },
  { word: "pad", clue: "A flattened mass of anything soft, to sit or lie on" },
  { word: "page", clue: "One of the many pieces of paper bound together within a book or similar document" },
  { word: "paint", clue: "A substance that is applied as a liquid or paste, and dries into a solid coating that protects or adds..." },
  { word: "papers", clue: "Official documents or identification, as a passport" },
  { word: "par", clue: "Equal value" },
  { word: "parade", clue: "An organized display of a group of people, particularly" },
  { word: "pardon", clue: "Forgiveness for an offence" },
  { word: "park", clue: "An area of land set aside for environment preservation or recreation" },
  { word: "part", clue: "A portion" },
  { word: "pass", clue: "To change place" },
  { word: "past", clue: "The period of time that has already happened, in contrast to the present and the future" },
  { word: "pat", clue: "The sound of a light slap or tap with a soft flat object, especially of a footstep" },
  { word: "patch", clue: "A piece of cloth, or other suitable material, sewed or otherwise fixed upon a garment to repair or..." },
  { word: "path", clue: "A trail for the use of, or worn by, pedestrians" },
  { word: "patron", clue: "One who protects or supports" },
  { word: "peak", clue: "A point" },
  { word: "period", clue: "A length of time" },
  { word: "pet", clue: "An animal kept as a companion" },
  { word: "phone", clue: "A device for transmitting conversations and other sounds in real time across distances, now often a small..." },
  { word: "pick", clue: "A tool used for digging" },
  { word: "pie", clue: "A type of pastry that consists of an outer crust and a filling" },
  { word: "piece", clue: "A part of a larger whole, usually in such a form that it is able to be separated from other parts" },
  { word: "pile", clue: "A mass of things heaped together" },
  { word: "pilot", clue: "A person who steers a ship, a helmsman" },
  { word: "pious", clue: "Of or pertaining to piety, exhibiting piety, devout, god-fearing" },
  { word: "pipe", clue: "Meanings relating to a wind instrument" },
  { word: "pit", clue: "A hole in the ground" },
  { word: "pitch", clue: "A sticky, gummy substance secreted by trees" },
  { word: "placed", clue: "put in position in relation to other things" },
  { word: "plan", clue: "A drawing showing technical details of a building, machine, etc" },
  { word: "plaza", clue: "A town's public square" },
  { word: "plea", clue: "An appeal, petition, urgent prayer or entreaty" },
  { word: "plus", clue: "A positive quantity" },
  { word: "poetic", clue: "Relating to poetry" },
  { word: "poetry", clue: "Literature composed in verse or language exhibiting conscious attention to patterns and rhythm" },
  { word: "point", clue: "A small dot or mark" },
  { word: "poison", clue: "A substance that is harmful or lethal to a living organism when ingested" },
  { word: "polar", clue: "Of or having a pole or polarity, as:" },
  { word: "pole", clue: "Originally, a stick" },
  { word: "policy", clue: "A principle of behaviour, conduct etc" },
  { word: "port", clue: "A place on the coast at which ships can shelter, or dock to load and unload cargo or passengers" },
  { word: "portal", clue: "An entrance, entry point, or means of entry" },
  { word: "post", clue: "A long dowel or plank protruding from the ground" },
  { word: "praise", clue: "Commendation" },
  { word: "prey", clue: "That which is or may be seized by animals to be devoured" },
  { word: "prize", clue: "That which is taken from another" },
  { word: "proc", clue: "A programmed random occurrence" },
  { word: "prone", clue: "Lying face-down" },
  { word: "prose", clue: "Language, particularly written language, not intended as poetry" },
  { word: "public", clue: "Able to be known or seen by everyone" },
  { word: "pulp", clue: "A soft, moist, shapeless mass or matter" },
  { word: "pump", clue: "A device for moving or compressing a liquid or gas" },
  { word: "purple", clue: "A colour between red and blue" },
  { word: "ray", clue: "A beam of light or radiation" },
  { word: "rim", clue: "An edge around something, especially when circular" },
  { word: "run", clue: "To move swiftly" },
  { word: "sac", clue: "A bag or pouch inside a plant or animal that typically contains a fluid" },
  { word: "sadly", clue: "In a sad manner" },
  { word: "safe", clue: "Not in danger" },
  { word: "sage", clue: "Wise" },
  { word: "said", clue: "Mentioned earlier" },
  { word: "salary", clue: "A fixed amount of money paid to a worker, usually calculated on a monthly or annual basis, not hourly, as..." },
  { word: "saline", clue: "Containing salt" },
  { word: "savage", clue: "Wild" },
  { word: "says", clue: "Mentioned earlier" },
  { word: "scared", clue: "Feeling fear" },
  { word: "scent", clue: "A distinctive smell" },
  { word: "scope", clue: "The breadth, depth or reach of a subject" },
  { word: "score", clue: "The total number of goals, points, runs, etc" },
  { word: "scream", clue: "A loud, emphatic, exclamation of extreme emotion, especially horror, fear, excitement, or anger" },
  { word: "screen", clue: "A physical divider intended to block an area from view, or provide shelter from something dangerous" },
  { word: "sea", clue: "A large body of salt water" },
  { word: "seat", clue: "Something to be sat upon" },
  { word: "shall", clue: "Used before a verb to indicate the simple future tense in the first person singular or plural" },
  { word: "shame", clue: "An uncomfortable or painful feeling due to recognition or consciousness of one's own impropriety or..." },
  { word: "shaped", clue: "Having been given a shape, especially a curved shape" },
  { word: "sharp", clue: "Terminating in a point or edge, especially one that can cut or pierce easily" },
  { word: "she", clue: "A female" },
  { word: "sheet", clue: "A thin bed cloth used as a covering for a mattress or as a layer over the sleeper" },
  { word: "shelf", clue: "A flat, rigid structure, fixed at right angles to a wall or forming a part of a cabinet, desk, etc" },
  { word: "shock", clue: "A sudden, heavy impact" },
  { word: "shook", clue: "A set of pieces for making a cask or box, usually wood" },
  { word: "shoot", clue: "To launch a projectile" },
  { word: "shop", clue: "An establishment that sells goods or services to the public" },
  { word: "shout", clue: "A loud burst of voice or voices" },
  { word: "shrine", clue: "A holy or sacred place dedicated to a specific deity, ancestor, hero, martyr, saint, or similar figure of..." },
  { word: "siege", clue: "Military action" },
  { word: "sir", clue: "A man of a higher rank or position" },
  { word: "sites", clue: "The place where anything is fixed" },
  { word: "size", clue: "The dimensions or magnitude of a thing" },
  { word: "slab", clue: "A large, flat piece of solid material" },
  { word: "slot", clue: "A narrow depression, perforation, or aperture" },
  { word: "slow", clue: "Taking a long time to move or go a short distance, or to perform an action" },
  { word: "social", clue: "Being extroverted or outgoing" },
  { word: "soft", clue: "Easily giving way under pressure" },
  { word: "softly", clue: "In a soft manner" },
  { word: "sole", clue: "Only" },
  { word: "solve", clue: "To find an answer or solution to a problem or question" },
  { word: "solved", clue: "Having a solution, having been explained or answered" },
  { word: "son", clue: "One's male offspring" },
  { word: "sore", clue: "Causing pain or discomfort" },
  { word: "sort", clue: "A general type" },
  { word: "sought", clue: "being searched for" },
  { word: "spot", clue: "A round or irregular patch on the surface of a thing having a different color, texture etc" },
  { word: "star", clue: "Any small, natural and bright dot appearing in the unobscured sky, especially in the night or twilight sky" },
  { word: "suite", clue: "A group or train of attendants, servants etc" },
  { word: "sure", clue: "Physically secure and certain, non-failing, reliable" },
  { word: "tab", clue: "A small flap or strip of material attached to or inserted into something, for holding, manipulation,..." },
  { word: "ten", clue: "A set or group with ten elements" },
  { word: "tie", clue: "A knot" },
  { word: "tip", clue: "The extreme end of something, especially when pointed" },
  { word: "toe", clue: "Each of the five digits on the end of the foot" },
  { word: "tom", clue: "The male of the domesticated cat, especially if not neutered" },
  { word: "ton", clue: "Any of various units of mass, originally notionally equal to the contents of a tun, particularly:" },
  { word: "vis", clue: "Force" },
];
