export interface WordEntry {
  word: string;
  clue: string;
  hint?: string;
}

export const WORD_BANK: WordEntry[] = [
  { word: "APPLE", clue: "Common red or green fruit", hint: "Keeps the doctor away" },
  { word: "ARROW", clue: "Projectile shot from a bow", hint: "Robin Hood's weapon" },
  { word: "ASTRO", clue: "Prefix relating to stars", hint: "Think astronaut or astronomy" },
  { word: "BALER", clue: "Farm machine that bundles hay", hint: "Makes round or square bundles" },
  { word: "BASIL", clue: "Herb often used in pesto", hint: "Green Italian herb" },
  { word: "BEACH", clue: "Sandy shore by the ocean", hint: "Where you build sandcastles" },
  { word: "BERRY", clue: "Small juicy fruit", hint: "Strawberry, blueberry, etc." },
  { word: "BISON", clue: "Large prairie grazer", hint: "Similar to buffalo" },
  { word: "BLADE", clue: "Sharp edge of a knife", hint: "The cutting part" },
  { word: "BLINK", clue: "Quick eye movement", hint: "Your eyes do this automatically" },
  { word: "BLOOM", clue: "Flower in blossom", hint: "Flowers do this in spring" },
  { word: "BOARD", clue: "Flat piece of wood", hint: "Used for planks or games" },
  { word: "BOLT", clue: "Metal fastener with threads", hint: "Used with a nut" },
  { word: "BONUS", clue: "Extra payment", hint: "A workplace reward" },
  { word: "BREAD", clue: "Loaf sliced for sandwiches", hint: "Sliced and toasted" },
  { word: "BRICK", clue: "Block used in masonry", hint: "Houses are built with these" },
  { word: "BRINE", clue: "Salty pickling solution", hint: "Pickles soak in this" },
  { word: "BROOM", clue: "Tool for sweeping", hint: "Witches fly on this" },
  { word: "BROWN", clue: "Color of chocolate", hint: "Mix red, yellow, and black" },
  { word: "BRUSH", clue: "Paint applicator", hint: "Artists use this with paint" },
  { word: "BUNNY", clue: "Playful name for a rabbit", hint: "Easter animal" },
  { word: "CABLE", clue: "Thick wire for electricity", hint: "TV or internet connection" },
  { word: "CACTI", clue: "Spiky desert plants", hint: "Plural of cactus" },
  { word: "CANDY", clue: "Sugary treat", hint: "Halloween haul" },
  { word: "CANOE", clue: "Narrow boat paddled by hand", hint: "Paddle it yourself" },
  { word: "CAPER", clue: "Pickled flower bud used as a garnish", hint: "Small green garnish" },
  { word: "CARAT", clue: "Gem weight unit", hint: "Diamond measurement" },
  { word: "CAROL", clue: "Festive song", hint: "Christmas song" },
  { word: "CARVE", clue: "Cut into a shape", hint: "What you do to a turkey" },
  { word: "CATCH", clue: "Snag in baseball", hint: "Opposite of throw" },
  { word: "CEDAR", clue: "Aromatic evergreen tree", hint: "Wood used for closets" },
  { word: "CHAIN", clue: "Series of linked metal rings", hint: "Used to lock a bike" },
  { word: "CHAIR", clue: "Seat with a back", hint: "Furniture to sit on" },
  { word: "CHANT", clue: "Repeated cheer", hint: "Stadium crowd does this" },
  { word: "CHART", clue: "Graph for data", hint: "Visual data display" },
  { word: "CHESS", clue: "Game with kings and queens", hint: "Black and white board game" },
  { word: "CHEST", clue: "Storage trunk", hint: "Pirate treasure container" },
  { word: "CHEWY", clue: "Texture of some caramel candy", hint: "Opposite of crunchy" },
  { word: "CHILI", clue: "Spicy stew", hint: "Spicy bean dish" },
  { word: "CHIME", clue: "Bells ringing together", hint: "Wind ___ on a porch" },
  { word: "CHIRP", clue: "Bird's tweet", hint: "Sound birds make" },
  { word: "CHOIR", clue: "Group of singers", hint: "Church singing group" },
  { word: "CHOPS", clue: "Cuts of meat from a rib", hint: "Pork or lamb cuts" },
  { word: "CIDER", clue: "Apple drink", hint: "Hot or cold apple beverage" },
  { word: "CIVIC", clue: "Relating to a city", hint: "Duty or responsibility to community" },
  { word: "CLASP", clue: "Fastening hook", hint: "Necklace fastener" },
  { word: "CLEAN", clue: "Free from dirt", hint: "Opposite of dirty" },
  { word: "CLERK", clue: "Office assistant", hint: "Store employee" },
  { word: "CLIFF", clue: "Steep rock face", hint: "Dangerous edge to fall from" },
  { word: "CLIMB", clue: "Ascend a mountain", hint: "Go up using hands and feet" },
  { word: "CLOCK", clue: "Wall timekeeper", hint: "Shows hours and minutes" },
  { word: "CLOTH", clue: "Woven fabric", hint: "Material for making clothes" },
  { word: "CLOUD", clue: "Sky puff", hint: "Fluffy white thing in the sky" },
  { word: "CLOWN", clue: "Circus comic", hint: "Wears red nose and big shoes" },
  { word: "CLUB", clue: "Society with shared interests", hint: "Book ___ meets monthly" },
  { word: "COAST", clue: "Seashore region", hint: "East or West in US" },
  { word: "COBRA", clue: "Hooded snake", hint: "Venomous snake from India" },
  { word: "COCOA", clue: "Hot chocolate ingredient", hint: "Brown powder from cacao" },
  { word: "COILS", clue: "Spiraled loops", hint: "Snake shape when resting" },
  { word: "COMET", clue: "Icy body with a tail in space", hint: "Halley's ___" },
  { word: "CONCH", clue: "Large sea snail shell" },
  { word: "CORAL", clue: "Reef-building organism" },
  { word: "CORK", clue: "Bottle stopper" },
  { word: "COUCH", clue: "Living room sofa" },
  { word: "COURT", clue: "Basketball playing surface" },
  { word: "CRAFT", clue: "Handmade project" },
  { word: "CRANE", clue: "Tall bird with long legs" },
  { word: "CRANK", clue: "Handle that turns a machine" },
  { word: "CRATE", clue: "Wooden shipping box" },
  { word: "CRAWL", clue: "Move on hands and knees" },
  { word: "CREAM", clue: "Whipped dessert topping" },
  { word: "CREEK", clue: "Small stream" },
  { word: "CREST", clue: "Top of a wave" },
  { word: "CRISP", clue: "Fresh and crunchy" },
  { word: "CROSS", clue: "Intersection symbol" },
  { word: "CROWD", clue: "Large gathering of people" },
  { word: "CROWN", clue: "Royal headpiece" },
  { word: "CRUSH", clue: "Infatuation" },
  { word: "CUBIC", clue: "Shaped like a box" },
  { word: "CUMIN", clue: "Spice in curry" },
  { word: "CURRY", clue: "Spiced stew" },
  { word: "CURVE", clue: "Bend in a road" },
  { word: "CYCLE", clue: "Repeat pattern" },
  { word: "DAISY", clue: "White-petaled flower" },
  { word: "DELTA", clue: "River mouth landform" },
  { word: "DENIM", clue: "Jeans fabric" },
  { word: "DIARY", clue: "Personal journal" },
  { word: "DICE", clue: "Pair of gaming cubes" },
  { word: "DIGIT", clue: "Numeral" },
  { word: "DINER", clue: "Casual roadside restaurant" },
  { word: "DIRGE", clue: "Funeral song" },
  { word: "DISCO", clue: "1970s dance music" },
  { word: "DIVER", clue: "Person exploring underwater" },
  { word: "DODGE", clue: "Avoid quickly" },
  { word: "DONUT", clue: "Ring-shaped pastry" },
  { word: "DOZEN", clue: "Twelve items" },
  { word: "DRAMA", clue: "Serious stage play" },
  { word: "DREAM", clue: "Sleeping vision" },
  { word: "DRIFT", clue: "Move with the current" },
  { word: "DRINK", clue: "Beverage" },
  { word: "DROOL", clue: "Saliva from a dog's mouth" },
  { word: "DROOP", clue: "Sag downward" },
  { word: "DROVE", clue: "Past tense of drive" },
  { word: "DRUID", clue: "Celtic priest" },
  { word: "DRUM", clue: "Percussion instrument" },
  { word: "DUCK", clue: "Quacking waterfowl" },
  { word: "DUNES", clue: "Hills of sand" },
  { word: "DWELL", clue: "Live in a place" },
  { word: "EAGLE", clue: "Majestic bird of prey" },
  { word: "EARTH", clue: "Our home planet" },
  { word: "EBONY", clue: "Dark hardwood" },
  { word: "EDICT", clue: "Official command" },
  { word: "ELFIN", clue: "Like a sprite" },
  { word: "ELITE", clue: "Group of top performers" },
  { word: "EMBER", clue: "Glowing coal" },
  { word: "EMOJI", clue: "Digital pictograph" },
  { word: "ENACT", clue: "Pass into law" },
  { word: "ENVOY", clue: "Diplomatic messenger" },
  { word: "EPOCH", clue: "Distinct period in history" },
  { word: "EQUAL", clue: "Exactly the same" },
  { word: "EQUIP", clue: "Provide tools" },
  { word: "ERASE", clue: "Remove pencil marks" },
  { word: "ESSAY", clue: "Formal written piece" },
  { word: "ETHER", clue: "Clear upper sky" },
  { word: "ETHIC", clue: "Moral principle" },
  { word: "EVENT", clue: "Planned occasion" },
  { word: "EXACT", clue: "Precisely correct" },
  { word: "EXALT", clue: "Lift in praise" },
  { word: "EXILE", clue: "Forced absence from one's country" },
  { word: "EXTRA", clue: "More than needed" },
  { word: "FABLE", clue: "Story with a moral" },
  { word: "FAITH", clue: "Belief without proof" },
  { word: "FAIRY", clue: "Winged folklore being" },
  { word: "FANCY", clue: "Elaborate or stylish" },
  { word: "FARMS", clue: "Agricultural lands" },
  { word: "FEAST", clue: "Large celebratory meal" },
  { word: "FENCE", clue: "Barrier around a yard" },
  { word: "FERNS", clue: "Shady green fronds" },
  { word: "FERRY", clue: "Boat carrying passengers" },
  { word: "FIBER", clue: "Dietary roughage" },
  { word: "FIELD", clue: "Open grassy area" },
  { word: "FIERY", clue: "Full of flames" },
  { word: "FILLY", clue: "Young female horse" },
  { word: "FINAL", clue: "Championship game" },
  { word: "FJORD", clue: "Narrow sea inlet between cliffs" },
  { word: "FLAKE", clue: "Snow crystal" },
  { word: "FLAME", clue: "Dancing fire" },
  { word: "FLASK", clue: "Bottle for liquids" },
  { word: "FLEET", clue: "Group of ships" },
  { word: "FLESH", clue: "Soft tissue" },
  { word: "FLICK", clue: "Quick movie" },
  { word: "FLINT", clue: "Hard stone that sparks" },
  { word: "FLORA", clue: "Plant life" },
  { word: "FLOUR", clue: "Baking staple" },
  { word: "FLUTE", clue: "High-pitched woodwind" },
  { word: "FOAM", clue: "Mass of tiny bubbles" },
  { word: "FOCUS", clue: "Concentrated attention" },
  { word: "FOGGY", clue: "Filled with mist" },
  { word: "FOLIO", clue: "Large book format" },
  { word: "FOND", clue: "Having affection" },
  { word: "FORCE", clue: "Strength or power" },
  { word: "FORGE", clue: "Shape metal with heat" },
  { word: "FORTH", clue: "Outward and onward" },
  { word: "FORTY", clue: "Four decades" },
  { word: "FORUM", clue: "Public discussion space" },
  { word: "FOSSIL", clue: "Preserved remains in rock" },
  { word: "FOXES", clue: "Cunning woodland animals" },
  { word: "FRAIL", clue: "Easily broken" },
  { word: "FRAME", clue: "Structure that supports" },
  { word: "FRESH", clue: "Recently made" },
  { word: "FRIAR", clue: "Member of a religious order" },
  { word: "FROST", clue: "Morning ice crystals" },
  { word: "FRUIT", clue: "Edible seed-bearing plant part" },
  { word: "FUDGE", clue: "Soft chocolate candy" },
  { word: "FUNGI", clue: "Mushroom family" },
  { word: "FUNNY", clue: "Causing laughter" },
  { word: "FURRY", clue: "Covered in soft hair" },
  { word: "GALE", clue: "Strong wind" },
  { word: "GAMER", clue: "Video game enthusiast" },
  { word: "GAVEL", clue: "Judge's mallet" },
  { word: "GEESE", clue: "Honking flock" },
  { word: "GENIE", clue: "Wish-granting spirit" },
  { word: "GENRE", clue: "Category of art" },
  { word: "GHOST", clue: "Spectral apparition" },
  { word: "GIANT", clue: "Mythical huge being" },
  { word: "GIFT", clue: "Present for someone" },
  { word: "GILDS", clue: "Medieval craft unions" },
  { word: "GLADE", clue: "Forest clearing" },
  { word: "GLASS", clue: "Material for windows" },
  { word: "GLEAM", clue: "Soft glowing light" },
  { word: "GLEAN", clue: "Gather bit by bit" },
  { word: "GLIDE", clue: "Move smoothly" },
  { word: "GLOBE", clue: "Model of Earth" },
  { word: "GLORY", clue: "Great honor" },
  { word: "GLOVE", clue: "Hand covering" },
  { word: "GLYPH", clue: "Carved symbol" },
  { word: "GNOME", clue: "Garden figurine" },
  { word: "GOATS", clue: "Bearded barnyard animals" },
  { word: "GOFER", clue: "Errand runner" },
  { word: "GOLD", clue: "Precious yellow metal" },
  { word: "GOLEM", clue: "Animated clay figure" },
  { word: "GOODS", clue: "Merchandise" },
  { word: "GRACE", clue: "Elegance under pressure" },
  { word: "GRADE", clue: "Score on a test" },
  { word: "GRAIN", clue: "Seed of cereal grass" },
  { word: "GRAPE", clue: "Fruit used for wine" },
  { word: "GRAPH", clue: "Data plot" },
  { word: "GRASS", clue: "Lawn covering" },
  { word: "GRAVE", clue: "Burial site" },
  { word: "GRIDS", clue: "Networks of lines" },
  { word: "GRILL", clue: "Outdoor cooking rack" },
  { word: "GRIND", clue: "Reduce to powder" },
  { word: "GRINS", clue: "Smiling faces" },
  { word: "GRIT", clue: "Courage under pressure" },
  { word: "GROVE", clue: "Small group of trees" },
  { word: "GROWN", clue: "Fully developed" },
  { word: "GRUEL", clue: "Thin hot cereal" },
  { word: "GUARD", clue: "Protective watcher" },
  { word: "GUEST", clue: "Invited visitor" },
  { word: "GUIDE", clue: "Person who leads the way" },
  { word: "GUILD", clue: "Association of artisans" },
  { word: "GULLY", clue: "Erosion ditch" },
  { word: "GUMMY", clue: "Sticky candy texture" },
  { word: "GUST", clue: "Sudden blast of wind" },
  { word: "GYM", clue: "Place for workouts" },
  { word: "HABIT", clue: "Repeated behavior" },
  { word: "HAIKU", clue: "Japanese short poem" },
  { word: "HAIRY", clue: "Covered with lots of fuzz" },
  { word: "HALO", clue: "Glow around a saint" },
  { word: "HAPPY", clue: "Feeling joyful" },
  { word: "HARDY", clue: "Able to survive tough conditions" },
  { word: "HARPS", clue: "Angelic instruments" },
  { word: "HASTE", clue: "Great hurry" },
  { word: "HATCH", clue: "Break out of an egg" },
  { word: "HAVEN", clue: "Safe harbor" },
  { word: "HAZEL", clue: "Light brown eye color" },
  { word: "HEART", clue: "Organ that pumps blood" },
  { word: "HEIST", clue: "Daring robbery" },
  { word: "HELIX", clue: "Twisting spiral" },
  { word: "HERO", clue: "Brave protagonist" },
  { word: "HIKER", clue: "Trail walker" },
  { word: "HILLS", clue: "Gentle rises in terrain" },
  { word: "HINGE", clue: "Door pivot" },
  { word: "HOBBY", clue: "Leisure pursuit" },
  { word: "HONOR", clue: "Great respect" },
  { word: "HONEY", clue: "Sweet bee product" },
  { word: "HORNS", clue: "Trumpet section" },
  { word: "HORSE", clue: "Animal with a mane" },
  { word: "HOTEL", clue: "Place to rent a room" },
  { word: "HOVER", clue: "Stay suspended in air" },
  { word: "HUMID", clue: "Muggy weather" },
  { word: "HUMOR", clue: "Sense of fun" },
  { word: "HUNCH", clue: "Intuitive guess" },
  { word: "HUSKY", clue: "Sled dog breed" },
  { word: "HYENA", clue: "Laughing scavenger" },
  { word: "ICING", clue: "Cake topping" },
  { word: "ICONS", clue: "Widely admired figures" },
  { word: "IDEAL", clue: "Perfect standard" },
  { word: "IDIOM", clue: "Phrase with nonliteral meaning" },
  { word: "IDLER", clue: "Person avoiding work" },
  { word: "IGLOO", clue: "Snow house" },
  { word: "IMAGE", clue: "Visual representation" },
  { word: "IMBUE", clue: "Fill with a quality" },
  { word: "IMPEL", clue: "Drive forward" },
  { word: "IMPLY", clue: "Suggest indirectly" },
  { word: "INBOX", clue: "Email landing spot" },
  { word: "INCAN", clue: "Relating to a Peruvian empire" },
  { word: "INDEX", clue: "Book locator section" },
  { word: "INDIE", clue: "Independent art scene" },
  { word: "INERT", clue: "Lacking motion" },
  { word: "INFER", clue: "Deduce from evidence" },
  { word: "INGOT", clue: "Metal casting bar" },
  { word: "INNER", clue: "Located on the inside" },
  { word: "INPUT", clue: "Information entered" },
  { word: "INSPIRE", clue: "Fill with creative energy" },
  { word: "INTER", clue: "Bury in the ground" },
  { word: "IONIC", clue: "Greek column style" },
  { word: "IRON", clue: "Wrinkle remover" },
  { word: "IRONY", clue: "Humorous contrast" },
  { word: "ISAAC", clue: "Biblical son saved from sacrifice" },
  { word: "ISLE", clue: "Small island" },
  { word: "ISSUE", clue: "Edition of a magazine" },
  { word: "IVORY", clue: "Creamy tusk material" },
  { word: "JAZZ", clue: "Improvised music style" },
  { word: "JEANS", clue: "Denim pants" },
  { word: "JELLO", clue: "Wiggly dessert" },
  { word: "JETTY", clue: "Pier for boats" },
  { word: "JEWEL", clue: "Precious stone" },
  { word: "JINX", clue: "Bring bad luck to" },
  { word: "JOKER", clue: "Wild card in a deck" },
  { word: "JOLLY", clue: "Full of cheer" },
  { word: "JOUST", clue: "Knightly duel" },
  { word: "JUDGE", clue: "Courtroom decision maker" },
  { word: "JUICE", clue: "Fruit beverage" },
  { word: "JUMBO", clue: "Extra large" },
  { word: "JUNGLE", clue: "Thick tropical forest" },
  { word: "JUNTO", clue: "Political faction" },
  { word: "JUROR", clue: "Member of a trial panel" },
  { word: "KARMA", clue: "Cosmic consequence" },
  { word: "KAYAK", clue: "Enclosed paddle boat" },
  { word: "KETTLE", clue: "Water heating pot" },
  { word: "KHAKI", clue: "Tan military cloth" },
  { word: "KICKS", clue: "Sneakers" },
  { word: "KITES", clue: "Windborne toys" },
  { word: "KOALA", clue: "Tree-hugging marsupial" },
  { word: "KUDOS", clue: "Words of praise" },
  { word: "LABEL", clue: "Sticker with information" },
  { word: "LACE", clue: "Delicate openwork fabric" },
  { word: "LAGER", clue: "Chilled beer style" },
  { word: "LAKES", clue: "Inland bodies of water" },
  { word: "LAMPS", clue: "Light-giving fixtures" },
  { word: "LANCE", clue: "Knight's spear" },
  { word: "LANDS", clue: "Touches down" },
  { word: "LAPEL", clue: "Fold on a suit jacket" },
  { word: "LASER", clue: "Focused light beam" },
  { word: "LATCH", clue: "Door fastener" },
  { word: "LATER", clue: "Opposite of sooner" },
  { word: "LATTE", clue: "Espresso with steamed milk" },
  { word: "LAUGH", clue: "Sound of amusement" },
  { word: "LAYER", clue: "Single thickness" },
  { word: "LEAFY", clue: "Full of foliage" },
  { word: "LEARN", clue: "Gain knowledge" },
  { word: "LEASH", clue: "Dog tether" },
  { word: "LEMON", clue: "Sour yellow fruit" },
  { word: "LEMUR", clue: "Ring-tailed primate" },
  { word: "LENDS", clue: "Gives temporarily" },
  { word: "LEVEL", clue: "Perfectly flat" },
  { word: "LEVER", clue: "Simple lifting machine" },
  { word: "LIBEL", clue: "Printed defamation" },
  { word: "LIBRA", clue: "Autumn zodiac sign" },
  { word: "LIDAR", clue: "Laser-based distance tech" },
  { word: "LILAC", clue: "Fragrant purple bloom" },
  { word: "LIMBO", clue: "State of uncertainty" },
  { word: "LIMIT", clue: "Upper boundary" },
  { word: "LIMON", clue: "Costa Rican port city" },
  { word: "LINEN", clue: "Flax fiber cloth" },
  { word: "LINGO", clue: "Specialized vocabulary" },
  { word: "LION", clue: "Big cat called king" },
  { word: "LIPID", clue: "Fat molecule" },
  { word: "LISPS", clue: "Speaks with a soft s" },
  { word: "LITER", clue: "Metric volume unit" },
  { word: "LIVID", clue: "Furiously angry" },
  { word: "LLAMA", clue: "Pack animal of the Andes" },
  { word: "LOAF", clue: "Bread shape" },
  { word: "LOBBY", clue: "Building entrance hall" },
  { word: "LOCAL", clue: "From nearby" },
  { word: "LODGE", clue: "Mountainside inn" },
  { word: "LOGIC", clue: "Rules of reasoning" },
  { word: "LOOMS", clue: "Weaving machines" },
  { word: "LOOPS", clue: "Curving turns" },
  { word: "LOTUS", clue: "Sacred water flower" },
  { word: "LOVER", clue: "Romantic partner" },
  { word: "LOWER", clue: "Bring down" },
  { word: "LOYAL", clue: "Faithfully devoted" },
  { word: "LUCID", clue: "Clear minded" },
  { word: "LUMEN", clue: "Unit of light output" },
  { word: "LUNAR", clue: "Relating to the moon" },
  { word: "LUNCH", clue: "Midday meal" },
  { word: "LUNGE", clue: "Sudden forward thrust" },
  { word: "LUPIN", clue: "Colorful garden flower" },
  { word: "LURCH", clue: "Sudden stagger" },
  { word: "LUSH", clue: "Rich with vegetation" },
  { word: "LYRIC", clue: "Song words" },
  { word: "MAGIC", clue: "Illusionist's craft" },
  { word: "MAIZE", clue: "Field corn" },
  { word: "MAJOR", clue: "Primary in importance" },
  { word: "MAKER", clue: "Creator or builder" },
  { word: "MANGO", clue: "Tropical stone fruit" },
  { word: "MAPLE", clue: "Tree that gives syrup" },
  { word: "MARBLE", clue: "Polished stone" },
  { word: "MARCH", clue: "Walk in formation" },
  { word: "MARES", clue: "Adult female horses" },
  { word: "MARRY", clue: "Join in wedlock" },
  { word: "MASSE", clue: "Curving billiards shot" },
  { word: "MATCH", clue: "Pair that goes together" },
  { word: "MATEY", clue: "Friendly pirate address" },
  { word: "MATH", clue: "Numbers subject" },
  { word: "MAUVE", clue: "Pale purple shade" },
  { word: "MAXIM", clue: "Pithy rule" },
  { word: "MAYOR", clue: "City leader" },
  { word: "MEADOW", clue: "Open grassy field" },
  { word: "MEDAL", clue: "Award on a ribbon" },
  { word: "MELEE", clue: "Chaotic skirmish" },
  { word: "MELON", clue: "Juicy summer fruit" },
  { word: "MERCY", clue: "Compassion" },
  { word: "MERGE", clue: "Combine into one" },
  { word: "MERIT", clue: "Earned praise" },
  { word: "METAL", clue: "Shiny conductive material" },
  { word: "METRO", clue: "Underground rail system" },
  { word: "MICRO", clue: "Extremely small" },
  { word: "MIGHT", clue: "Great strength" },
];
